[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "futhorc-language"
version = "1.0.1"
description = "A statically typed programming language with ASCII and Anglo-Saxon runic vocabularies"
readme = "README.md"
requires-python = ">=3.10"

authors = [
    { name = "Matalya" }
]

license = "GPL-3.0-only"
license-files = ["LICENSE"]

keywords = [
    "programming-language",
    "interpreter",
    "static-typing",
    "futhorc",
    "runes",
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Interpreters",
]

[project.urls]
Homepage = "https://github.com/Matalya/futhorc"
Repository = "https://github.com/Matalya/futhorc"
Documentation = "https://github.com/Matalya/futhorc"
Issues = "https://github.com/Matalya/futhorc/issues"

[project.scripts]
futhorc = "thorn:main"

[tool.setuptools]
py-modules = [
    "thorn",
    "lexer",
    "parser",
    "semantic",
    "interpreter",
    "runtime",
    "module_system",
    "th_ast",
    "Token",
]