[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "futhorc-language"
version = "0.1.0"
description = "The Thorn programming language interpreter"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["pyperclip>=1.8"]

[project.scripts]
futhorc = "thorn:main"

[tool.setuptools]
py-modules = [
    "thorn",
    "lexer",
    "parser",
    "semantic",
    "interpreter",
    "runtime",
    "module_system",
    "th_ast",
    "Token"
]
